AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.3
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - lib/generators/**/*
    - lib/rails/generators/**/*
    - lib/populate/**/*
    - bin/*
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
Metrics/ClassLength:
  CountComments: false
  Max: 100
  Exclude:
    - test/**/*
Metrics/ClassLength:
  CountComments: false
  Max: 300
  Include:
    - test/**/*
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
Metrics/BlockLength:
  Enabled: false
  Include:
    - test/**/*
Style/PredicateName:
  Enabled: true
  Exclude:
    - test/support/shoulda/**/*
Style/PredicateName:
  Enabled: false
  Include:
    - test/support/shoulda/**/*
Style/AsciiComments:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
